/*!CK:3116235207!*//*1421165327,*/

(self.TimeSlice ? self.TimeSlice.guard : function(f) { return f; })(function() {if (self.CavalryLogger) { CavalryLogger.start_js(["aOnc+"]); }

__d("DevappImageSelector",["Event","copyProperties"],function(a,b,c,d,e,f,g,h){function i(j,k,l){g.listen(j,'click',function(){i.getPreviewDialog().show(k,l);});}h(i,{_previewDialog:null,setPreviewDialog:function(j){i._previewDialog=j;},getPreviewDialog:function(){return i._previewDialog;}});e.exports=i;},null);
__d("DeveloperAppAppDetailsImageHandler",["CSS","cx","DOM","Event"],function(a,b,c,d,e,f,g,h,i,j){var k={init:function(l){l.forEach(function(m){var n=i.find(m,'input');j.listen(n,'click',function(event){return this._click(n);}.bind(this));}.bind(this));},_click:function(l){var m=i.find(document,'div.'+"_5try"+("[data-platform=\""+l.value+"\"]"));g.conditionShow(m,l.checked);this._updateScreenshotCardState();this._updateBannerCardState();},_updateBannerCardState:function(){var l=i.scry(document,'div.'+"_59fh"+'.'+"_5trz"+' input'),m=false;l.forEach(function(o){return m=m||o.checked;});var n=i.scry(document,'div.'+"_5trw");n.forEach(function(o){return g.conditionClass(o,"_5trx",!m);});},_updateScreenshotCardState:function(){var l=i.scry(document,'div.'+"_5try"+':not(.hidden_elem)'),m=i.find(document,'div.'+"_5tr-");g.conditionShow(m,l.length);}};e.exports=k;},null);
__d("DeveloperCategorySelector",["CSS"],function(a,b,c,d,e,f,g){var h={init:function(i,j,k){this.handleChange(i,j,k);i.subscribe('change',this.handleChange.bind(this,i,j,k));},handleChange:function(i,j,k){if(i.getValue()!=k){g.hide(j);}else g.show(j);}};e.exports=h;},null);
__d("DeveloperAsyncDialog",["AsyncRequest","copyProperties","CSS","cx","DOM"],function(a,b,c,d,e,f,g,h,i,j,k){function l(m){this.dialog=m;this.statusElement=k.find(m.getRoot(),'.'+"_2uf");this.contentElement=k.find(m.getRoot(),'.'+"_2ug");}h(l.prototype,{show:function(m,n){this.showStatus();this.dialog.show();new g(m).setMethod('POST').setData(n).setHandler(this._handleData.bind(this)).send();},_handleData:function(m){k.setContent(this.contentElement,m.getPayload());this.hideStatus();},hideStatus:function(m,n){i.show(this.contentElement);i.hide(this.statusElement);},showStatus:function(m,n){i.hide(this.contentElement);i.show(this.statusElement);}});e.exports=l;},null);

}, 'remote script ')();